#!/usr/bin/env python3

from mtag.widget import MTagWindow

import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk


def start_mtag():
    _ = MTagWindow()
    Gtk.main()

if __name__ == "__main__":
    start_mtag()
