#!/usr/bin/env python3

from http.server import HTTPServer
from mtag.web import RequestHandler


if __name__ == '__main__':
    host = "127.0.0.1"
    port = 8000
    http_server = HTTPServer((host, port), RequestHandler)
    print(f"Started web server at http://{host}:{port}")
    try:
        http_server.serve_forever()
    except KeyboardInterrupt:
        pass
